from fastapi import FastAPI

from models import CellSiteInfo
from faker_util import create_fake_site

app = FastAPI()


@app.get("/getSiteDetails", response_model=CellSiteInfo)
def get_site_details():
    """Return fake cell site details generated by Faker."""
    return create_fake_site()


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("network-agent.main:app", host="0.0.0.0", port=8000, reload=True)